---

- block:
    - validate:
        schema:
          type: object
          properties:
            stackdriver_enabled:
              type: boolean
              default: no
          required:
            - stackdriver_enabled
        instance: "{{ fail2ban }}"
      register: fail2ban_validated

    - set_fact:
        fail2ban_v: "{{ fail2ban_validated.result }}"

    - block:
        - name: 'Install fail2ban and supporting packages'
          apt:
            name:
              - python-pyinotify # enables more efficient file watching
              - fail2ban
            state: present

        - name: "Install Slack notification action"
          template:
            src: slack.conf.j2
            dest: /etc/fail2ban/action.d/slack.conf

        - name: 'Remove unnecessary default files'
          file:
            path: '/etc/fail2ban/jail.d/defaults-debian.conf'
            state: absent
          notify: fail2ban_restart
      become: yes

    - import_role:
        name: bedrock.stackdriver
      vars:
        stackdriver:
          command: configure_logging_agent
          config: |
            <source>
              @type tail
              <parse>
                @type regexp
                expression /^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})\s+fail2ban\.(?<module>\w+)\s+\[\d+\]: (?<level>[A-Z]+)\s+(?<message>.*)$/
                time_format %Y-%m-%d %H:%M:%S,%L
              </parse>
              path /var/log/fail2ban.log
              pos_file /var/lib/google-fluentd/pos/fail2ban.pos
              tag fail2ban
            </source>
            <filter fail2ban>
              @type record_transformer
              enable_ruby
              renew_record true
              keep_keys level,module
              <record>
                hostname ${hostname}
                message ${hostname + " " + record["message"]}
              </record>
            </filter>

          filename: fail2ban
      when: fail2ban_v.stackdriver_enabled
  tags:
    - fail2ban_install
