---

- validate:
    schema:
      type: object
      properties:
        command:
          type: string
          enum:
            - create_sshd_jail
            - dependency
            - install
      required:
        - command
    instance: "{{ fail2ban }}"

- include_tasks: '{{ fail2ban.command }}.yml'
  when: fail2ban.command != 'dependency'
